# Generated by Django 5.2.7 on 2025-12-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_age_user_height_user_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='happiness_index',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
