# Generated by Django 5.2.7 on 2025-12-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_happiness_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='scores',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
