# Generated by Django 5.2.7 on 2025-12-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_current_streak_user_last_streak_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='badges',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
