# Generated by Django 4.2.20 on 2026-02-05 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_user_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='happinessrecord',
            name='scores',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
