# Generated by Codex on 2026-02-06
from django.db import migrations, models
import django.db.models.deletion


def seed_if_questions(apps, schema_editor):
    IFQuestion = apps.get_model('api', 'IFQuestion')
    questions = [
        {"key": "s_steps", "label": "Nivel de actividad física (Pasos)", "order": 1},
        {"key": "s_sleep", "label": "Horas de sueño promedio", "order": 2},
        {"key": "s_stress_inv", "label": "Manejo del estrés (10 = Excelente, 1 = Pésimo)", "order": 3},
        {"key": "s_intensity", "label": "Intensidad de entrenamientos", "order": 4},
        {"key": "s_emotional", "label": "Estabilidad emocional", "order": 5},
        {"key": "s_social", "label": "Vida social y conexiones", "order": 6},
        {"key": "s_hrv", "label": "Variabilidad cardíaca (Sensación de recuperación)", "order": 7},
        {"key": "s_bio_age", "label": "Edad Biológica (Percepción de vitalidad)", "order": 8},
        {"key": "s_sleep_quality", "label": "Calidad del sueño", "order": 9},
        {"key": "s_circadian", "label": "Sincronización ritmo circadiano (Rutina)", "order": 10},
        {"key": "s_focus", "label": "Capacidad de enfoque", "order": 11},
        {"key": "s_mood_sust", "label": "Estado de ánimo sostenido", "order": 12},
        {"key": "s_flow", "label": "Frecuencia de estado de Flow", "order": 13},
        {"key": "s_purpose", "label": "Sentido de propósito", "order": 14},
        {"key": "s_hobbies", "label": "Tiempo dedicado a hobbies", "order": 15},
        {"key": "s_prosocial", "label": "Actitudes prosociales (Ayudar a otros)", "order": 16},
    ]
    for q in questions:
        IFQuestion.objects.update_or_create(key=q["key"], defaults=q)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_user_profile_extras'),
    ]

    operations = [
        migrations.CreateModel(
            name='IFQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='IFAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_id', models.CharField(max_length=10)),
                ('slot', models.CharField(blank=True, choices=[('morning', 'morning'), ('afternoon', 'afternoon'), ('night', 'night')], max_length=12, null=True)),
                ('value', models.PositiveSmallIntegerField()),
                ('source', models.CharField(default='app', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.ifquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='if_answers', to='api.user')),
            ],
            options={
                'unique_together': {('user', 'question', 'week_id')},
            },
        ),
        migrations.RunPython(seed_if_questions, migrations.RunPython.noop),
    ]
