# Generated by Codex on 2026-02-06
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_if_questions_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='ifanswer',
            name='answered_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterUniqueTogether(
            name='ifanswer',
            unique_together={('user', 'question', 'week_id', 'answered_date', 'slot')},
        ),
    ]
