# Generated by Codex on 2026-02-06
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_ifanswer_answered_date_unique_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trial_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='trial_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='billing_status',
            field=models.CharField(default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_provider',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='current_period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_payment_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
