# Generated by Django 6.0.2 on 2026-02-19 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_user_coach_state_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=80)),
                ('entity_type', models.CharField(blank=True, default='', max_length=40)),
                ('entity_id', models.CharField(blank=True, default='', max_length=120)),
                ('before_json', models.JSONField(blank=True, null=True)),
                ('after_json', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['occurred_at'], name='api_auditlo_occurre_7df9a1_idx'), models.Index(fields=['action'], name='api_auditlo_action_0a1743_idx'), models.Index(fields=['entity_type', 'entity_id'], name='api_auditlo_entity__ad4253_idx')],
            },
        ),
    ]
