# Generated by Django 6.0.2 on 2026-02-21 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_auditlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="QAFSoftMemoryPortion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("item_id", models.CharField(max_length=80)),
                ("grams_last", models.FloatField()),
                ("count_confirmed", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qaf_soft_memory_portions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "item_id")},
                "indexes": [
                    models.Index(fields=["user", "item_id"], name="api_qafsoft_user_it_5cf4d9_idx"),
                    models.Index(fields=["user", "updated_at"], name="api_qafsoft_user_up_9e5b48_idx"),
                ],
            },
        ),
    ]
