# Generated by Copilot on 2026-02-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_qafsoftmemoryportion"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="goal_type",
            field=models.CharField(
                blank=True,
                choices=[("deficit", "deficit"), ("maintenance", "maintenance"), ("gain", "gain")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="activity_level",
            field=models.CharField(
                blank=True,
                choices=[("low", "low"), ("moderate", "moderate"), ("high", "high")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="daily_target_kcal_override",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
