# Generated by Django 6.0.1 on 2026-02-07 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_fitnesssync'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fitnesssync',
            new_name='devices_fit_user_id_686220_idx',
            old_name='devices_fit_user_pr_1964ea_idx',
        ),
    ]
