# Generated by Django 6.0.1 on 2026-02-17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0003_rename_devices_fit_user_pr_1964ea_idx_devices_fit_user_id_686220_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSyncCheckpoint",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=40)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_checkpoints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "key")},
                "indexes": [models.Index(fields=["user", "key"], name="devices_usersy_user_id_2cd53a_idx")],
            },
        ),
        migrations.CreateModel(
            name="SyncRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(blank=True, default="", max_length=40)),
                ("reason", models.CharField(blank=True, default="", max_length=80)),
                ("priority", models.IntegerField(default=5)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("running", "running"),
                            ("done", "done"),
                            ("error", "error"),
                            ("skipped", "skipped"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True, default="")),
                ("result", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["status", "priority", "requested_at"], name="devices_syncre_status_4f52e9_idx"),
                    models.Index(fields=["user", "status"], name="devices_syncre_user_id_47d0a2_idx"),
                ],
            },
        ),
    ]
