# Generated by Django 6.0.1 on 2026-02-19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0004_sync_scheduler_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhoopRawRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("cycle", "cycle"),
                            ("sleep", "sleep"),
                            ("recovery", "recovery"),
                            ("workout", "workout"),
                            ("profile", "profile"),
                            ("body", "body"),
                        ],
                        max_length=20,
                    ),
                ),
                ("resource_id", models.CharField(max_length=100)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("created_at_remote", models.DateTimeField(blank=True, null=True)),
                ("updated_at_remote", models.DateTimeField(blank=True, null=True)),
                ("timezone_offset", models.CharField(blank=True, default="", max_length=8)),
                ("score_state", models.CharField(blank=True, default="", max_length=20)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whoop_raw_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "resource_type", "resource_id")},
                "indexes": [
                    models.Index(fields=["user", "resource_type"], name="devices_whoop_user_type_idx"),
                    models.Index(fields=["resource_type", "resource_id"], name="devices_whoop_type_id_idx"),
                ],
            },
        ),
    ]
